- src/components/Home.tsx
- src/components/main/HotContents.tsx
- src/components/main/HotContentsCard.tsx
style: add main page hot contents list
> style: add main page hot contents list

- src/apis/apis.ts
> Feat: "Add api about contents"

- src/apis/apis.ts
- src/components/comment/Comment.tsx
- src/components/comment/CommentInput.tsx
- src/components/comment/CommentItem.tsx
- src/components/postModal/PostModal.tsx
- src/components/postModal/PostModalPlace.tsx
- src/components/share/Dropdown.tsx
- src/function/getToday.ts
- src/model/interface.ts
- src/pages/Home.tsx
add comment style
add comment patch, delete, post api
> Feat: "Add comment style & api"

- src/apis/apis.ts
- src/components/comment/Comment.tsx
- src/components/comment/CommentDropdown.tsx
- src/components/comment/CommentInput.tsx
- src/components/comment/CommentItem.tsx
- src/components/detailModal/DetailContentsModal.tsx
- src/components/detailModal/DetailModalFooter.tsx
- src/components/detailModal/DetailModalHeader.tsx
- src/components/detailModal/DetalModalBody.tsx
- src/components/main/HotContents.tsx
- src/components/main/HotContentsCard.tsx
- src/components/main/RecentCard.tsx
- src/components/main/RecentContents.tsx
- src/components/postModal/PostModal.tsx
- src/model/interface.ts
- src/pages/Contents.tsx
- src/pages/Home.tsx
- src/shared/Router.tsx
add comment styling and CRUD api
> Feat: "Add Comment CRUD"

- package.json
- src/components/share/LocationDropdown.tsx
- src/components/share/LocationFilter.tsx
- src/function/kakao.ts
- src/pages/Home.tsx
- yarn.lock
add location info feature and style
> Feat: "Add Location Info"

- src/components/main/RecentContents.tsx
- src/components/main/skeleton/RecentCardAddressSkeleton.tsx
- src/components/main/skeleton/hotContentsSkeleton.css
- src/components/main/skeleton/recentCardSkeleton.css
- src/pages/Contents.tsx
- 게시글 목록 페이지에 스켈레톤 로딩 화면 구현.
- 메인 페이지 최근 게시글 스켈레톤 로딩 화면 수정.
- 작동 확인 후, 정상 작동 시 로딩 처리만 부탁드립니다.
> Style: Contents skeleton

- package.json
- src/pages/Login.tsx
- src/pages/Signup.tsx
- src/shared/Routers.tsx
- yarn.lock
- 로그인 페이지 생성 및 스타일링
- js-cookie 라이브러리 설치
- 기본 로그인 POST 요청, 액세스 토큰은 쿠키 보관, 리프레쉬 토큰은 로컬스토리지 보관 (현재 expire 미기입)
- 카카오 OAuth2 로그인 API 추가 예정
- 이후 서버와 연동하여 쿠키 토큰 전달 확인 및 인가 확인 후, 수정 예정
> Feat: Login

- src/components/auth/KakaoLogin.tsx
- src/components/auth/KakaoLogin2.tsx
- src/pages/Login.tsx
- 카카오 로그인 API 환경 설정 및 로그인 기능 추가
- 이용 필수 정보: 이메일(아이디), 이름, 프로필 이미지
- 정상 로그인 작동, 메인 페이지('/') 리다이렉션 작동 확인
- 토큰 처리 결과, refreshToken과 accessToken을 발급 받고, 서비스에서 제공하는 기본적인 만료 시간이 있음.
- KakaoLogin2 컴포넌트의 경우, 트러블 슈팅으로 인해 임시 활용했던 부분, 현재 쓰이지 않으나 서버에 연결하고 수정할 때 처리할 예정.
- 토큰과 비동기 요청 함수, API 등은 BE 배포 후에 추가로 수정할 예정
> Feat: OAuth 2.0 Kakao login

- src/components/auth/KakaoLogin.tsx
- src/components/share/NavDropdown.tsx
- src/pages/Login.tsx
- src/pages/Signup.tsx
- 기본 로그인 시스템 로그아웃 기능 추가(navbar dropdown)
> Feat: logout

- src/components/comment/Input.tsx
- src/components/main/RecentContents/index.tsx
- src/components/main/comment/Card.tsx
- src/components/main/comment/index.tsx
- src/components/main/hotContents/index.tsx
- src/components/postModal/Image2.tsx
- src/components/postModal/index.tsx
- src/components/posts/index.tsx
- src/components/share/Carousel.tsx
- src/hooks/reactQuery/comment/useDeleteCommentMutation.tsx
- src/hooks/reactQuery/comment/usePostCommentMutation.tsx
- src/hooks/reactQuery/main/useGetCommentPostsQuery.tsx
- src/hooks/reactQuery/main/useGetRecentPostsQuery.tsx
- src/hooks/reactQuery/post/useGetAllContentsQuery.tsx
- src/hooks/reactQuery/post/useGetContentDetailQuery.tsx
- src/hooks/reactQuery/post/usePostContentQuery.tsx
- src/model/interface.ts
> Feat : "add main recent category"

- src/axios/authApi.ts
- src/components/auth/signup/Register.tsx
- src/hooks/reactQuery/mypage/useGetMyBookmarkQuery.ts
- src/hooks/reactQuery/mypage/useGetMyPostsQuery.ts
- src/hooks/reactQuery/mypage/useGetUserDataQuery.ts
- src/pages/Mypage.tsx
- src/pages/SignUp.tsx
- 마이페이지 요청 3개 수정
- 무한 스크롤 적용
- 현재 무한 스크롤 관련 요청에 오류 부분 존재 -> 수정 예정
> Fix: My page

- src/components/posts/index.tsx
- src/hooks/reactQuery/mypage/useGetMyPostsQuery.ts
- src/pages/Mypage.tsx
- 마이페이지 GET 요청 수정
- 무한 스크롤 테스트는 아직 -> 유저 테스트 배포 이후, 테스트하고 수정할 예정
> Fix: My page Get request

- src/pages/googleMap/map/MapGoogle.tsx
> Fix: "fix map default zoom level"

- src/components/share/NavDropdown.tsx
- src/pages/Login.tsx
> Fix: "fix user store missing"

- src/hooks/reactQuery/auth/useLoginMutation.tsx
- src/pages/Login.tsx
> Design: "fix login theme"

- src/components/auth/mypage/edit/ProfileEdit.tsx
- src/hooks/reactQuery/mypage/useUpdateMyImageMutation.ts
- src/shared/Routers.tsx
- 프로필 이미지 수정 관련 alert 제거 -> 테스트 배포 후에 이미지 수정과 프로필 내용 수정 통합 예정
> Fix: Profile edit bug fix

- src/components/auth/mypage/edit/ProfileEdit.tsx
- src/components/auth/mypage/edit/ProfileImage.tsx
- 배포 빌드 오류 발생
- 원인으로 추정되는 import 경로 수정
> Fix: import path

- src/components/auth/mypage/PlaceCard.tsx
- src/hooks/reactQuery/mypage/useGetMyBookmarkQuery.ts
- src/pages/Mypage.tsx
- 북마크 데이터 수정
- 북마크 장소 디테일 모달 onClick에 추가
> Fix: My bookmarks

- src/components/auth/mypage/PlaceCard.tsx
> Fix: my bookmark address fix

- src/axios/authAuth.ts
- src/components/auth/mypage/edit/ProfileImage.tsx
- src/pages/Login.tsx
- src/pages/Mypage.tsx
- 프로필 수정 페이지, 마이페이지 등 일부 버그 Fix
- 마이페이지 북마크, 게시글 각각 존재하지 않을 시, 문구 추가
> Fix: bug fix

- src/components/button/BookMarkButton.tsx
- src/components/comment/Input.tsx
- src/components/comment/Item.tsx
- src/components/comment/RepleInput.tsx
- src/hooks/reactQuery/replies/usePostRepleMutation.tsx
- src/styles/GlobalStyle.tsx
- src/styles/font.css
- vercel.json
- vite.config.ts
> Fix: "fix font apply"

- package.json
- src/components/auth/mypage/edit/ProfileImage.tsx
- src/components/auth/signup/Register.tsx
- src/components/comment/Item.tsx
- src/components/comment/RepleItem.tsx
- src/pages/ProfileEdit.tsx
- src/pages/UserPage.tsx
- src/pages/postDetail/DetailModalHeader.tsx
- yarn.lock
- 게시글, 댓글, 대댓글 유저 프로필 사진 또는 이름 클릭 시 유저 페이지 이동
- 마이페이지 피드백 기반 수정 - 프로필 사진 수정 클릭 범위, 이메일 input -> text 등
- 글자 수 제한 피드백 기반 수정 - 비밀번호 입력, 닉네임 범위 등
> Fix: feedback

- src/components/comment/Item.tsx
- src/components/comment/RepleItem.tsx
- src/components/navbar/search/UserResultItem.tsx
- src/pages/Login.tsx
- src/pages/Mypage.tsx
- src/pages/ProfileEdit.tsx
- src/pages/SignUp.tsx
- src/pages/UserPage.tsx
- src/pages/postDetail/DetailModalHeader.tsx
- 마이페이지, 로그인, 유저페이지 접근 등 제한 처리
> Fix: restrict Unauth user

- package-lock.json
- package.json
- src/components/Modal/LocationModal.tsx
- src/components/button/Button.test.tsx
- src/components/card/HotPostsCard.tsx
- src/components/share/dropdown/locationDropdown/Menu.tsx
- src/components/test/test-utils.ts
- src/components/textarea/PostTextArea.tsx
- src/hooks/useObserver.ts
- src/pages/googleMap/placeList/PlaceList.tsx
- src/pages/patch/PatchModal.tsx
- src/pages/posts/list/List.tsx
- vite.config.ts
- yarn.lock
> Fix : "fix styling and patch text"

- src/components/auth/signup/Done.tsx
- src/components/auth/signup/Register.tsx
- src/components/button/authButton/LargeButton.tsx
- src/components/button/authButton/SmallButton.tsx
- src/components/input/authInput/Input1.tsx
- src/components/text/Text1.tsx
- src/components/text/Title1.tsx
- src/pages/Login.tsx
- src/pages/Mypage.tsx
- src/pages/ProfileEdit.tsx
- src/pages/SignUp.tsx
> Style: styled components (not finished)
